### ISSUE TITLE
Remove ads

### ISSUE THREAD

**Issue by Stylix58** [Tronic247/material-docs#12]
You can remove ads, please? Because, on all frameworks documentation I see, they don't have any ads.
PS: if you want to get money with this, you can use OpenCollective!

**Comment by Tronic247** [comment]
OpenCollective is for donations , but when we put ads we earn from clicks.

**Comment by Stylix58** [comment]
Yes but documentation must does't have any ads, or people will hate navigation in docs because of that.

**Comment by Tronic247** [comment]
@Stylix58 Then where to put ads ? in the bottom or a sidebar ?

**Comment by Stylix58** [comment]
In the bottom, after the contributors image.

**Comment by Tronic247** [comment]
OK
