### ISSUE TITLE
Not mobile friendly and bug with edit button ripple

### ISSUE THREAD

**Issue by Stylix58** [Tronic247/material-docs#8]
![image](https://user-images.githubusercontent.com/63605602/124899736-b35fcb00-dfe0-11eb-8885-ad9ba3a3c9e6.png)

See #6 and #7 for more informations (scroll to the bottom for really see).

Also, the ripple of the button see to be hidden on click.

**Comment by Tronic247** [comment]
@Stylix58 I know it is not mobile friendly. Because developers mostly use this documentation by using a computer or a laptop, not phones or tabs:D
And the ripple effect is not working because the ripple color is also blue. I changed it.

**Comment by Stylix58** [comment]
You can just remove the two button of the appbar, the same links is or can be added to homepage!

**Comment by Tronic247** [comment]
@Stylix58 I removed one button and replaced one button as an icon. Please wait 5min and see the website.

**Comment by Stylix58** [comment]
![image](https://user-images.githubusercontent.com/63605602/124903806-9fb66380-dfe4-11eb-9c1e-88c7ffcab5f9.png)
